-- Writers remain concurrent. A reader publishes only committed events to a
-- durable feed, serializing the short publication transaction per collection.
CREATE TABLE record_event_feed (
  event_id text PRIMARY KEY REFERENCES record_events(event_id) ON DELETE CASCADE,
  space_id text NOT NULL,
  collection_id text NOT NULL,
  position bigint GENERATED BY DEFAULT AS IDENTITY UNIQUE
);
CREATE INDEX record_event_feed_scoped_position
  ON record_event_feed(space_id,collection_id,position);

-- Older events are all committed before this migration completes. Their
-- historic timestamps supply a stable initial order only.
INSERT INTO record_event_feed(event_id,space_id,collection_id)
  SELECT event_id,space_id,collection_id FROM record_events
  ORDER BY committed_at,event_id;
